force-app/main/default/objects/Programme_Participant__c/Programme_Participant__c.object-meta.xml
<CustomObject>
    <label>Programme Participant</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Programme Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Programme Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Programme_Participant__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>Used in the Learning Lounge Lightning Community</description>
    <label>Cohort</label>
    <referenceTo>TL_Programme__c</referenceTo>
    <relationshipLabel>Programme Participants (Cohort)</relationshipLabel>
    <relationshipName>Programme_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Programme_Participant__c/fields/Cohort_Name__c.field-meta.xml
<CustomField>
    <fullName>Cohort_Name__c</fullName>
    <formula>Cohort__r.Cohort_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cohort Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Programme_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Programme Participants</relationshipLabel>
    <relationshipName>Programme_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programme_Participant__c/fields/Programme__c.field-meta.xml
<CustomField>
    <fullName>Programme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Programme</label>
    <referenceTo>TL_Programme__c</referenceTo>
    <relationshipLabel>Programme Participants</relationshipLabel>
    <relationshipName>Programme_Participants1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Programme_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used in the Learning Lounge Lightning Community</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Participant_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TL_Programme__c/TL_Programme__c.object-meta.xml
<CustomObject>
    <label>ML Programme</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Programme Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TL_Programme__c/fields/Cohort_Name__c.field-meta.xml
<CustomField>
    <fullName>Cohort_Name__c</fullName>
    <description>Used in the Learning Lounge Lightning Community</description>
    <label>Cohort Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TL_Programme__c/fields/LMS_Access__c.field-meta.xml
<CustomField>
    <fullName>LMS_Access__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Canvas Access</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TL_Programme__c/fields/LMS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>LMS_End_Date__c</fullName>
    <inlineHelpText>If the Canvas End Date has passed participants will have been removed from the course and extending it WILL NOT give them access again.  To extend access change the Canvas Start Date as required.</inlineHelpText>
    <label>Canvas End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TL_Programme__c/fields/LMS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>LMS_Start_Date__c</fullName>
    <label>Canvas Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TL_Programme__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Programmes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TL_Programme__c/fields/Programme_Definition__c.field-meta.xml
<CustomField>
    <fullName>Programme_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used in the Learning Lounge Lightning Community</description>
    <label>Programme Definition</label>
    <referenceTo>Programme_Definition__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TL_Programme__c/recordTypes/Cohort.recordType-meta.xml
<RecordType>
    <fullName>Cohort</fullName>
    <active>true</active>
    <description>This should be used for all non-MLP/ALP programmes and is used to store Cohort info related to a Programme</description>
    <label>Cohort</label>
</RecordType>

force-app/main/default/classes/LMSTest.cls
@isTest
private class LMSTest {
    static Programme_Definition__c prDef;
    static Opportunity o;
    static Contact c;
    static {
        Test.setMock(HttpCalloutMock.class, new CanvasAPIMock());

        prDef = new Programme_Definition__c(Programme__c='Test', Status__c='Active');
        insert prDef;
        
        Account a = new Account(Name='TestAccount');
        insert a;
        
        c = new Contact(FirstName = 'Test', LastName= 'Test', AccountId = a.Id, Email='test@example.org');
        insert c;
        
        o = new Opportunity(Name='Test', AccountId=a.Id, Package_del__c='Independant cycle',
            StageName='Completed', Type='Small group', CloseDate=Date.today());
        insert o;
    }

    @isTest private static void TestLMSCourseProvisionTrigger() {
        TL_Programme__c cohort = new TL_Programme__c(
            Programme_Definition__c=prDef.Id,
            Opportunity__c=o.Id,
            Cohort_Name__c='Test 1',
            LMS_Access__c=true,
            LMS_Start_Date__c=Date.today(),
            LMS_End_Date__c=Date.today() + 1
        );

        insert cohort;
    }

    @isTest private static void TestLMSProgrammeParticipantStatusTrigger() {
        TL_Programme__c cohort = new TL_Programme__c(
            Programme_Definition__c=prDef.Id,
            Opportunity__c=o.Id,
            Cohort_Name__c='Test 1',
            LMS_Access__c=true,
            LMS_Start_Date__c=Date.today(),
            LMS_End_Date__c=Date.today() + 1
        );

        insert cohort;

        Test.startTest();
        Programme_Participant__c participant = new Programme_Participant__c(
            Cohort__c=cohort.Id,
            Participant__c=c.Id,
            Status__c='Active'
        );
        insert participant;

        participant.Status__c = 'Inactive';

        update participant;

        Test.stopTest();
    }
}